version: "3.8"
services:
  devcontainer:
    container_name: "${COMPOSE_PROJECT_NAME}"
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: "nvidia"
    #           count: 1
    #           capabilities: [gpu]
  db:
    container_name: "postgres_database"
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database
  adminer:
    image: adminer
    ports:
      - 1080:8080
